---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by laiiiii.
--- DateTime: 2026/3/11 下午7:40
---

--[[
    解锁 Lua 脚本
    功能：验证锁的归属并安全释放锁
    参数说明：
        KEYS[1]: 锁的 key（lock:锁名称）
        ARGV[1]: 当前线程的唯一标识符
    返回值：
        成功删除锁返回 1
        锁不属于当前线程或锁不存在返回 0
]]--
-- 比较线程标识与锁中的标识是否一致
if(redis.call('get', KEYS[1]) == ARGV[1]) then
    -- 只有当前线程持有锁时才执行删除操作
    return redis.call('del', KEYS[1])
end
return 0